apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  labels:
    app: product-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - name: product-catalog
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=product-catalog service - version 1.0"
          ports:
            - containerPort: 5678
