apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-catalog
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: product-catalog
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
