networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  tempo_data:

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ../week4/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../week1/recording_rules.yml:/etc/prometheus/recording_rules.yml
      - ../week1/alerting_rules.yml:/etc/prometheus/alerting_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki
      - tempo

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro,rslave
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host/root'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    volumes:
      - ../week2/loki-config.yml:/etc/loki/local-config.yaml
      - ../week2/loki-rules:/loki/rules/fake
      - loki_data:/loki
    command:
      - '--config.file=/etc/loki/local-config.yaml'
    ports:
      - "3100:3100"
    networks:
      - monitoring

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - 'run'
      - '--server.http.listen-addr=0.0.0.0:12345'
      - '/etc/alloy/config.alloy'
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    networks:
      - monitoring
    depends_on:
      - loki
      - tempo

  tempo:
    image: grafana/tempo:2.6.1
    container_name: tempo
    restart: unless-stopped
    user: root
    volumes:
      - ../week3/tempo-config.yml:/etc/tempo/config.yml
      - tempo_data:/var/tempo
    command:
      - '--config.file=/etc/tempo/config.yml'
    ports:
      - "3200:3200"
    networks:
      - monitoring

  order-api:
    build:
      context: ../week4/app
    container_name: order-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - monitoring
    depends_on:
      - alloy
